### ISSUE TITLE
Fail to get avatar

### ISSUE THREAD

**Issue by manzato** [masihyeganeh/yahoomessenger-js#9]
Under certain circumstances (don't know really which) the library tries to fetch the avatar using `friendIconDownload` which doesn't exist.

**Comment by manzato** [comment]
Here is a log of a failed execution:

```
/tmp/sample/bundle/programs/server/npm/yahoo-wrapper/node_modules/yahoomessenger/lib/incoming/various.js:122
    return context.friendIconDownload(username);
                   ^
TypeError: Object #<EventEmitter> has no method 'friendIconDownload'
    at getAvatar (/tmp/sample/bundle/programs/server/npm/yahoo-wrapper/node_modules/yahoomessenger/lib/incoming/various.js:122:20)
    at EventEmitter.<anonymous> (/tmp/sample/bundle/programs/server/npm/yahoo-wrapper/node_modules/yahoomessenger/lib/incoming/various.js:159:18)
    at PacketParameters.foreach (/tmp/sample/bundle/programs/server/npm/yahoo-wrapper/node_modules/yahoomessenger/lib/packetparameters.js:34:32)
    at EventEmitter.buddyInfo (/tmp/sample/bundle/programs/server/npm/yahoo-wrapper/node_modules/yahoomessenger/lib/incoming/various.js:141:11)
    at EventEmitter.onConnectionDataReceive (/tmp/sample/bundle/programs/server/npm/yahoo-wrapper/node_modules/yahoomessenger/lib/messenger.js:135:24)
    at EventEmitter.emit (events.js:106:17)
    at EventEmitter.handlePackets (/tmp/sample/bundle/programs/server/npm/yahoo-wrapper/node_modules/yahoomessenger/lib/connection.js:90:10)
    at EventEmitter.handlePackets (/tmp/sample/bundle/programs/server/npm/yahoo-wrapper/node_modules/yahoomessenger/lib/connection.js:86:10)
    at Socket.tryToConnectOnData (/tmp/sample/bundle/programs/server/npm/yahoo-wrapper/node_modules/yahoomessenger/lib/connection.js:24:10)
    at Socket.emit (events.js:95:17)
```
